### 1. contents 만들기
POST http://localhost:8080/api/contents
Content-Type: application/json

{
  "title": "test title",
  "content": "test content",
  "price": 0,
  "discountRate": 0,
  "isFree": true
}

### 2. Content 북마크 등록
POST http://localhost:8080/api/bookmark
Authorization: Bearer {{access_token}}

### 3. Content 북마크 해제
DELETE http://localhost:8080/api/bookmark
Authorization: Bearer {{access_token}}

### 4. 인증 없이 북마크 가능한지?
POST http://localhost:8080/api/bookmark