@host = http://localhost:8080
@creatorId = 1

### [Withdrawal] 1) 출금 가능 잔액 조회
GET {{host}}/api/creators/{{creatorId}}/settlements/available-balance
Accept: application/json


### [Withdrawal] 2) 출금 신청 (정상)
POST {{host}}/api/creators/{{creatorId}}/withdrawals
Content-Type: application/json
Accept: application/json

{
  "amount": 1000
}


### [Withdrawal] 3-1) 출금 내역 조회 - 이번 달 기본
GET {{host}}/api/creators/{{creatorId}}/withdrawals?page=0&size=20
Accept: application/json

### [Withdrawal] 3-2) 출금 내역 조회 - 월 지정
GET {{host}}/api/creators/{{creatorId}}/withdrawals?month=2026-01&page=0&size=20
Accept: application/json

### [Withdrawal] 3-3) 출금 내역 조회 - 월 지정 (첫 페이지)
GET {{host}}/api/creators/{{creatorId}}/withdrawals?month=2026-01&page=0&size=5
Accept: application/json

### [Withdrawal] 3-4) 출금 내역 조회 - 월 지정 (두 번째 페이지)
GET {{host}}/api/creators/{{creatorId}}/withdrawals?month=2026-01&page=1&size=5
Accept: application/json


### [Withdrawal] 4-1) 출금 내역 조회 실패 - 잘못된 월 값
GET {{host}}/api/creators/{{creatorId}}/withdrawals?month=2026-13&page=0&size=20
Accept: application/json

### [Withdrawal] 4-2) 출금 내역 조회 실패 - 잘못된 월 형식
GET {{host}}/api/creators/{{creatorId}}/withdrawals?month=2026/01&page=0&size=20
Accept: application/json


### [Withdrawal] 5-1) 출금 신청 실패 - 금액 0
POST {{host}}/api/creators/{{creatorId}}/withdrawals
Content-Type: application/json
Accept: application/json

{
  "amount": 0
}

### [Withdrawal] 5-2) 출금 신청 실패 - 음수 금액
POST {{host}}/api/creators/{{creatorId}}/withdrawals
Content-Type: application/json
Accept: application/json

{
  "amount": -10
}

### [Withdrawal] 5-3) 출금 신청 실패 - 잔액 부족
POST {{host}}/api/creators/{{creatorId}}/withdrawals
Content-Type: application/json
Accept: application/json

{
  "amount": 999999999
}
